#!/bin/sh

set -e

case "$1" in
configure)
  # Remove leftover stop symlinks from /etc/rc[016].d/. These used to be
  # installed some time ago, this was stopped, but these were never cleaned up.
  for i in 0 1 6 ; do
    [ -f /etc/rc$i.d/K*sysfsutils ] && rm /etc/rc$i.d/K*sysfsutils
  done
  ;;
abort-upgrade|abort-remove|abort-deconfigure)
  ;;
*)
  echo "postinst called with unknown argument '$1'" >&2
  exit 1
  ;;
esac

#DEBHELPER#

exit 0
